/**
 * Cross-validation tests: TypeScript vs Python reference outputs.
 *
 * These tests use exact inputs generated by NumPy (np.random.seed(42) and
 * np.random.seed(43)) and compare the TypeScript outputs against the
 * Python `compute.py` outputs, captured to full float64 precision.
 *
 * This is the definitive proof that the TS port produces identical results
 * to the Python implementation.
 *
 * Tolerance: 1e-12 (well below the 1e-6 acceptance criterion).
 */

import { scalePmf, responseEmbeddingsToPmf } from "../compute";
import type { Vector, Matrix } from "../types";

// ---------------------------------------------------------------------------
// Tolerance
// ---------------------------------------------------------------------------

/** Maximum allowed absolute difference between Python and TS outputs. */
const TOL = 1e-12;

function expectClose(actual: number, expected: number, label: string) {
  const diff = Math.abs(actual - expected);
  if (diff > TOL) {
    throw new Error(
      `${label}: expected ${expected}, got ${actual} (diff=${diff}, tol=${TOL})`
    );
  }
}

function expectVectorClose(actual: Vector, expected: Vector, label: string) {
  expect(actual.length).toBe(expected.length);
  for (let i = 0; i < actual.length; i++) {
    expectClose(actual[i], expected[i], `${label}[${i}]`);
  }
}

function expectMatrixClose(actual: Matrix, expected: Matrix, label: string) {
  expect(actual.length).toBe(expected.length);
  for (let i = 0; i < actual.length; i++) {
    expectVectorClose(actual[i], expected[i], `${label}[${i}]`);
  }
}

// ---------------------------------------------------------------------------
// Exact inputs from NumPy (np.random.seed(42), np.random.randn(3, 10))
// ---------------------------------------------------------------------------

const RESPONSE_EMBS: Matrix = [
  [0.4967141530112327, -0.13826430117118466, 0.6476885381006925, 1.5230298564080254, -0.23415337472333597, -0.23413695694918055, 1.5792128155073915, 0.7674347291529088, -0.4694743859349521, 0.5425600435859647],
  [-0.46341769281246226, -0.46572975357025687, 0.24196227156603412, -1.913280244657798, -1.7249178325130328, -0.5622875292409727, -1.0128311203344238, 0.3142473325952739, -0.9080240755212111, -1.4123037013352917],
  [1.465648768921554, -0.22577630048653566, 0.06752820468792384, -1.4247481862134568, -0.5443827245251827, 0.11092258970986608, -1.1509935774223028, 0.37569801834567196, -0.600638689918805, -0.2916937497932768],
];

// np.random.seed(43), np.random.randn(10, 5)
const LIKERT_EMBS: Matrix = [
  [0.25739992534469325, -0.9084814327806607, -0.37850310605882326, -0.5349155987755707, 0.8580733460716252],
  [-0.41300998231472696, 0.49818858448728287, 2.0101992475719856, 1.2628615445176543, -0.43921485686763406],
  [-0.34643789298865063, 0.4553196595572467, -1.6686627070136322, -0.8620854950098128, 0.49291084812374153],
  [-0.12431339614548602, 1.9351362874003422, -0.6184426549843884, -1.0468389862150573, -0.8896175886602026],
  [0.01404053719712835, -0.16082968616578383, 2.2303596488319384, -0.39911571852552363, 0.05444456336457185],
  [0.8841818151951191, -0.10798056134293389, 0.5556069842518202, 0.3949066359501769, 0.8372050226472976],
  [-1.4078781703965773, 0.8078494136349023, -0.13828364464101, 0.18717858533399576, -0.38665813551339834],
  [1.6590487297919925, -2.0470691310925226, 1.3993169863061743, -0.6790071212021919, 1.5289851345959593],
  [1.2212159632534685, 1.0149885167826984, 0.8281299823497013, 2.2662927082101914, -0.5949556701334289],
  [-0.5812695375284159, -0.6558941461838667, 0.9251488533568732, -1.2991613442508536, 1.0111668672107617],
];

// ---------------------------------------------------------------------------
// Python reference outputs (captured to full float64 precision)
// ---------------------------------------------------------------------------

const PYTHON = {
  scale_pmf_t1: [0.1, 0.2, 0.3, 0.4],
  scale_pmf_t05: [0.03333333333333333, 0.13333333333333333, 0.29999999999999993, 0.5333333333333333],
  scale_pmf_t2: [0.16270045344786255, 0.2300931878702196, 0.2818054517861928, 0.3254009068957251],
  scale_pmf_t0: [0.0, 0.0, 0.0, 1.0],
  scale_pmf_capped: [0.2719830267262223, 0.38919930183064844, 0.3388176714431293],

  pmf_no_eps: [
    [0.11219068930333626, 0.3841158095519402, 0.17012875198690877, 0.0, 0.33356474915781464],
    [0.34125317957832835, 0.010290268024834204, 0.0, 0.32189068168229906, 0.32656587071453835],
    [0.29694897774268453, 0.0, 0.162012886059993, 0.1753456139713768, 0.36569252222594545],
  ],

  pmf_eps_01: [
    [0.1013070151808972, 0.34685254535060456, 0.15362447781780703, 0.09701049338427938, 0.30120546826641165],
    [0.30418022201595923, 0.009172357064234589, 0.10863769125368607, 0.2869212211882589, 0.2910885084778612],
    [0.28125775377418205, 0.052841481684100605, 0.1534518851086656, 0.1660800919223209, 0.3463687875107306],
  ],

  pmf_single: [
    [0.11219068930333626, 0.3841158095519402, 0.17012875198690877, 0.0, 0.33356474915781464],
  ],

  scaled_pmf_row_t05: [0.04190820859909955, 0.491258218491417, 0.09636978644353789, 0.0, 0.37046378646594547],
  scaled_pmf_row_t2: [0.1722334732852764, 0.3186913256508582, 0.21209381776386166, 0.0, 0.29698138330000373],
};

// ===================================================================
// Tests
// ===================================================================

describe("Cross-validation: scalePmf vs Python", () => {
  const pmf1: Vector = [0.1, 0.2, 0.3, 0.4];

  it("temperature=1.0 (identity)", () => {
    expectVectorClose(scalePmf(pmf1, 1.0), PYTHON.scale_pmf_t1, "scale_pmf_t1");
  });

  it("temperature=0.5 (sharpen)", () => {
    expectVectorClose(scalePmf(pmf1, 0.5), PYTHON.scale_pmf_t05, "scale_pmf_t05");
  });

  it("temperature=2.0 (smooth)", () => {
    expectVectorClose(scalePmf(pmf1, 2.0), PYTHON.scale_pmf_t2, "scale_pmf_t2");
  });

  it("temperature=0.0 (one-hot)", () => {
    expectVectorClose(scalePmf(pmf1, 0.0), PYTHON.scale_pmf_t0, "scale_pmf_t0");
  });

  it("temperature capped at maxTemp=5.0", () => {
    expectVectorClose(
      scalePmf([0.1, 0.6, 0.3], 100.0, 5.0),
      PYTHON.scale_pmf_capped,
      "scale_pmf_capped"
    );
  });
});

describe("Cross-validation: responseEmbeddingsToPmf vs Python", () => {
  it("3 responses, epsilon=0.0", () => {
    const result = responseEmbeddingsToPmf(RESPONSE_EMBS, LIKERT_EMBS, 0.0);
    expectMatrixClose(result, PYTHON.pmf_no_eps, "pmf_no_eps");
  });

  it("3 responses, epsilon=0.1", () => {
    const result = responseEmbeddingsToPmf(RESPONSE_EMBS, LIKERT_EMBS, 0.1);
    expectMatrixClose(result, PYTHON.pmf_eps_01, "pmf_eps_01");
  });

  it("single response, epsilon=0.0", () => {
    const result = responseEmbeddingsToPmf([RESPONSE_EMBS[0]], LIKERT_EMBS, 0.0);
    expectMatrixClose(result, PYTHON.pmf_single, "pmf_single");
  });

  it("empty response array returns empty", () => {
    const result = responseEmbeddingsToPmf([], LIKERT_EMBS, 0.0);
    expect(result).toEqual([]);
  });
});

describe("Cross-validation: scalePmf on computed PMF vs Python", () => {
  it("temperature=0.5 on first PMF row", () => {
    const pmfRow = responseEmbeddingsToPmf([RESPONSE_EMBS[0]], LIKERT_EMBS, 0.0)[0];
    expectVectorClose(
      scalePmf(pmfRow, 0.5),
      PYTHON.scaled_pmf_row_t05,
      "scaled_pmf_row_t05"
    );
  });

  it("temperature=2.0 on first PMF row", () => {
    const pmfRow = responseEmbeddingsToPmf([RESPONSE_EMBS[0]], LIKERT_EMBS, 0.0)[0];
    expectVectorClose(
      scalePmf(pmfRow, 2.0),
      PYTHON.scaled_pmf_row_t2,
      "scaled_pmf_row_t2"
    );
  });
});

describe("Cross-validation: PMF properties match Python", () => {
  it("zero probabilities appear at same positions as Python", () => {
    const result = responseEmbeddingsToPmf(RESPONSE_EMBS, LIKERT_EMBS, 0.0);

    // Python row 0 has a zero at index 3
    expect(result[0][3]).toBe(0);
    // Python row 1 has a zero at index 2
    expect(result[1][2]).toBe(0);
    // Python row 2 has a zero at index 1
    expect(result[2][1]).toBe(0);
  });

  it("each row sums to exactly 1.0 (within 1e-15)", () => {
    const result = responseEmbeddingsToPmf(RESPONSE_EMBS, LIKERT_EMBS, 0.0);
    for (let i = 0; i < result.length; i++) {
      const rowSum = result[i].reduce((a, b) => a + b, 0);
      expect(Math.abs(rowSum - 1.0)).toBeLessThan(1e-15);
    }
  });
});
